pelican:
  whoami: production
  target: asf-site
publish:
  whoami: asf-site

github:
  description: "Apache Lucene website"
  labels:
    - apache
    - lucene
    - website
    - pelican
  enabled_merge_buttons:
    squash: true
    merge:  true
    rebase: false
  protected_branches:
    main
    production
  features:
    # Enable issues management
    issues: true
