pelican:
  whoami: main/solr
  target: solrtlp-staging

staging:
  whoami: solrtlp-staging
  profile: solrtlp

github:
  labels:
    - apache
    - solr
    - website
    - pelican
  enabled_merge_buttons:
    squash: true
    merge:  true
    rebase: false
  protected_branches:
    main
    production
