pelican:
  whoami: main
  target: asf-staging

staging:
  whoami: asf-staging

github:
  labels:
    - apache
    - lucene
    - website
    - pelican
  enabled_merge_buttons:
    squash: true
    merge:  true
    rebase: false
  protected_branches:
    main
    production
  features:
    # Enable issues management
    issues: true
