pelican:
  whoami: master
  target: asf-staging

staging:
  whoami: asf-staging

github:
  labels:
    - lucene
    - website
    - pelican
  enabled_merge_buttons:
    squash: true
    merge:  true
    rebase: false
  protected_branches:
    master
    production
